"""Profile-likelihood parity for ``threshold(..., interval_method="profile")`` against the
independent R offset-trick reference (plan sections 5.4, 6.2), read from
``tools/drc_reference/finney71_profile.json``. **Never runs R.**

That fixture is generated by an R implementation of the *same* offset trick plan section 5.4
prescribes for marginkit's own profile solver -- ``deviance(glm(cbind(n-succ, succ) ~ 0 +
I(log(x)-theta), offset=zstar, family=binomial(link="probit")))``, rooted with ``uniroot`` -- on
the finney71 ``dose>0`` subset, fixed ``upper=1, lower=0``, at the ED50 (``zstar =
qnorm(0.5) = 0``). It is an independent implementation of the same mathematics, not a second
copy of drc's own (delta-only) ``ED()``, so this is the one fixture in the suite that can
directly parity-check marginkit's profile endpoints rather than only its point estimate.

**Definitional note on the endpoint tolerance (not absorbed silently, plan section 6.1).** A
scratch prototype of marginkit's own offset-trick solver, run against this same fixture, gave:

    theta_hat            ours=1.578048742802   R=1.578048742952   diff=1.5e-10
    profile CI on theta   ours=[1.474331934697, 1.677347379378]
                          R   =[1.474302809704, 1.677369510157]
    profile CI on dose    ours=[4.368116611,    5.351342047]
                          R   =[4.367989391,     5.351460478]
    relative error: lo 2.91e-05, hi 2.21e-05

``generate.R`` calls ``uniroot`` with no ``tol`` argument, so it roots at R's default
``.Machine$double.eps^0.25 ~= 1.2207e-4`` on ``theta``; both residuals above sit inside that.
marginkit's own profile solver is specified (plan section 5.4) to bracket with
``scipy.optimize.brentq``, which this project runs at a much tighter ``xtol`` elsewhere
(``tools/drc_reference/README.md`` records the same pattern for the under-converged
``LN.3``/``LN.4`` drc fits: drc's own optimizer, not marginkit's, is the looser side). **The
residual between marginkit and this fixture, at the 1e-3 relative endpoint tolerance plan
section 6.1 sets, is therefore the fixture's own root-finding imprecision, not evidence of a
marginkit bug** -- a future reader seeing this test pass with room to spare should not read that
as marginkit being imprecise; it is the reference that stops short.

``theta_hat`` (and therefore ``value``, its exponential) comes from a converged GLM on both
sides of the R/Python boundary and needs no such allowance: it is checked at a tight ``1e-8``
relative, matching the ``1.5e-10`` the prototype above actually reached.

The final check is independent of R's tolerance entirely: at each of marginkit's own returned
endpoints, ``2 * (llf_hat - llf_profile(endpoint))`` must equal ``scipy.stats.chi2.ppf(level,
1)`` -- the exact condition ``brentq`` was rooting for. This is verified with a second,
from-scratch Python implementation of the same offset-trick deviance (not a call into
``marginkit.threshold`` internals), so it checks marginkit's own root-finding self-consistently,
independently of both drc and of ``finney71_profile.json``'s own numeric precision.
"""

from __future__ import annotations

import json
import math
from pathlib import Path
from typing import Any

import numpy as np
import pytest
from numpy.typing import NDArray
from scipy.stats import chi2
from statsmodels.genmod import families
from statsmodels.genmod.generalized_linear_model import GLM

from marginkit import Axis, Definition, Observations, Status, fit_dose_response, threshold

_FIXTURE_DIR = Path(__file__).resolve().parents[2] / "tools" / "drc_reference"
_REL_TOL_THETA_HAT = 1e-8
_REL_TOL_ENDPOINTS = 1e-3
# Absolute tolerance on the chi-square self-consistency check (target ~3.84 at level=0.95): two
# independently-converged GLM fits (one at theta_hat, one at each endpoint) carry their own IRLS
# floating-point noise, which is not itself bounded by marginkit's own brentq xtol. 1e-4 is
# roughly four orders of magnitude inside the target value, comfortably tighter than plan
# section 6.1's ordinary tolerances while not chasing noise from a second, unrelated optimizer.
_CHI2_ABS_TOL = 1e-4


def _load(name: str) -> dict[str, Any]:
    with (_FIXTURE_DIR / name).open() as fh:
        result: dict[str, Any] = json.load(fh)
    return result


def _finney71_observations() -> Observations:
    fixture = _load("finney71.json")
    dose = fixture["dataset"]["dose"]
    total = fixture["dataset"]["total"]
    affected = fixture["dataset"]["affected"]
    successes = [t - a for t, a in zip(total, affected, strict=True)]
    axis = Axis(name="dose", unit="unit", scale="log")
    return Observations.from_counts(
        axis,
        severity=dose,
        successes=successes,
        trials=total,
        outcome="success",
        direction="decreasing",
    )


def _nonzero_dose_arrays() -> tuple[NDArray[np.float64], NDArray[np.float64], NDArray[np.float64]]:
    fixture = _load("finney71.json")
    dose = np.array(fixture["dataset"]["dose"], dtype=np.float64)
    total = np.array(fixture["dataset"]["total"], dtype=np.float64)
    affected = np.array(fixture["dataset"]["affected"], dtype=np.float64)
    successes = total - affected
    nonzero = dose > 0.0
    return dose[nonzero], successes[nonzero], total[nonzero]


def _profile_deviance(
    theta: float,
    dose: NDArray[np.float64],
    successes: NDArray[np.float64],
    trials: NDArray[np.float64],
) -> float:
    """An independent, from-scratch reimplementation of the plan section 5.4/6.2 offset trick,
    at ``zstar=0`` (the ED50, matching ``finney71_profile.json``'s own scope): the same
    no-intercept GLM plan section 5.4 specifies for marginkit's own profile solver, built here
    directly against ``statsmodels`` rather than by calling into ``marginkit.threshold``.
    """
    covariate = (np.log(dose) - theta).reshape(-1, 1)
    failures = trials - successes
    endog = np.column_stack([failures, successes])
    model = GLM(endog, covariate, family=families.Binomial(link=families.links.Probit()))
    result = model.fit()
    return float(result.deviance)


class TestProfileParity:
    """finney71, probit, fixed ``upper=1, lower=0``, ED50 -- against the offset-trick reference
    in ``finney71_profile.json``.
    """

    def test_value_and_endpoints_match_the_offset_trick_reference(self) -> None:
        fixture = _load("finney71_profile.json")

        obs = _finney71_observations()
        fit = fit_dose_response(obs, model="binomial", link="probit", upper=1.0, lower=0.0)
        assert fit.status is Status.OK

        t = threshold(
            fit,
            definition=Definition.absolute(0.5),
            interval_method="profile",
            level=fixture["level"],
        )

        assert t.interval_method == "profile"
        assert t.value == pytest.approx(fixture["ed50_dose_hat"], rel=_REL_TOL_THETA_HAT)
        assert t.lo == pytest.approx(fixture["profile_ci_dose"]["lo"], rel=_REL_TOL_ENDPOINTS)
        assert t.hi == pytest.approx(fixture["profile_ci_dose"]["hi"], rel=_REL_TOL_ENDPOINTS)

    def test_endpoints_satisfy_the_profile_deviance_condition_independent_of_r(self) -> None:
        """At each returned endpoint, ``2*(llf_hat - llf_profile(endpoint))`` must equal the
        target chi-square quantile -- the exact condition marginkit's own ``brentq`` root-finder
        is specified to solve (plan section 5.4). Checked with a second, independent Python
        implementation of the offset-trick deviance, so this holds regardless of R's own
        precision or of ``finney71_profile.json``'s numbers at all.
        """
        fixture = _load("finney71_profile.json")
        dose, successes, trials = _nonzero_dose_arrays()

        obs = _finney71_observations()
        fit = fit_dose_response(obs, model="binomial", link="probit", upper=1.0, lower=0.0)
        t = threshold(
            fit,
            definition=Definition.absolute(0.5),
            interval_method="profile",
            level=fixture["level"],
        )
        assert t.value is not None and t.lo is not None and t.hi is not None

        min_deviance = _profile_deviance(math.log(t.value), dose, successes, trials)
        chi2_target = float(chi2.ppf(fixture["level"], 1))

        for endpoint in (t.lo, t.hi):
            endpoint_deviance = _profile_deviance(math.log(endpoint), dose, successes, trials)
            assert (endpoint_deviance - min_deviance) == pytest.approx(
                chi2_target, abs=_CHI2_ABS_TOL
            )
