"""Reference-value parity against R's ``drc`` package (plan sections 6.1, 6.2; Phase 4 plan).

Every expected number here is read from the JSON fixtures under ``tools/drc_reference/``,
generated by ``tools/drc_reference/generate.R`` inside the pinned ``rocker/r-ver:4.6.1``
container (see ``tools/drc_reference/README.md``). **This file never runs R and never needs R
installed** -- it reads only the committed JSON.

Tolerances: plan section 6.1 sets ``1e-4`` relative on parameters and log-likelihood, and
``1e-3`` relative on interval endpoints (the latter not exercised yet -- ``ED``/``EDcomp``/
profile parity are Phase 5/6 fixtures, read by later test-author work, not by this file). It
says nothing about covariance. ``decisions/0007``'s "Reference tolerances for covariance"
amendment sets covariance parity against drc's ``vcov`` at ``1e-3`` relative, because drc's
``vcov`` comes from a finite-difference Hessian inside its own optimizer (about ``1.3e-4`` away
from an independent numerical Hessian on finney71, per ``finney71.json``'s
``observed_hessian_check``) -- not the ordinary ``1e-4`` parameter bound. The internal
consistency check between the GLM path and the likelihood path
(``TestGlmPathMatchesLikelihoodPathNearBoundary``) has no such excuse and is held at the full
``1e-4``.

A failing test here is a reference-value drift: the fixed-asymptote GLM path this exercises is
the one part of Phase 4 with an independent, non-marginkit implementation to check against. Per
``CLAUDE.md``, that failure is a finding, never resolved by loosening the tolerance or adjusting
the expected value.
"""

from __future__ import annotations

import json
import math
from pathlib import Path
from typing import Any

import numpy as np
import pytest

from marginkit import Axis, Observations, Status, fit_dose_response

_FIXTURE_DIR = Path(__file__).resolve().parents[2] / "tools" / "drc_reference"
_REL_TOL_PARAMS = 1e-4
# decisions/0007's "Reference tolerances for covariance" amendment: covariance against drc's
# LN.2/LL.2 vcov is compared at 1e-3 relative, not the ordinary 1e-4 parameter tolerance --
# drc's vcov comes from a numerical Hessian inside its own optimizer and sits about 1.3e-4 away
# from an independent numerical Hessian even on drc's own coefficients (finney71.json's
# observed_hessian_check), so 1e-4 is not attainable against drc itself.
_REL_TOL_COV = 1e-3
# The internal consistency check between the GLM path and the GenericLikelihoodModel path (on
# the same data, with the likelihood path's asymptotes pinned a hair inside (0, 1)) has no such
# excuse -- both sides are marginkit's own computation of the same quantity -- and is held at
# the ordinary 1e-4 (decisions/0007's amendment).
_REL_TOL_PATH_CONSISTENCY = 1e-4


def _load(name: str) -> dict[str, Any]:
    with (_FIXTURE_DIR / name).open() as fh:
        result: dict[str, Any] = json.load(fh)
    return result


def _matrix(fixture_block: dict[str, Any]) -> np.ndarray:
    return np.array(fixture_block["values"], dtype=float)


def _finney71_observations(axis_scale: str = "log") -> Observations:
    fixture = _load("finney71.json")
    dose = fixture["dataset"]["dose"]
    total = fixture["dataset"]["total"]
    affected = fixture["dataset"]["affected"]
    # marginkit tracks SUCCESS; finney71's "affected" plays the role of failure (fixture note,
    # and the Phase 4 plan's "Mapping into marginkit" section), so successes = total - affected.
    successes = [t - a for t, a in zip(total, affected, strict=True)]
    axis = Axis(name="dose", unit="unit", scale=axis_scale)
    return Observations.from_counts(
        axis,
        severity=dose,
        successes=successes,
        trials=total,
        outcome="success",
        direction="decreasing",
    )


def _delta_transform_drc_be_covariance(
    b: float, e: float, *, s_sign: float, sigma_be: np.ndarray
) -> np.ndarray:
    """The natural-scale ``(mu, s)`` covariance from drc's own ``(b, e)`` covariance via the
    delta method (decisions/0007: the covariance parity reference is drc's ``vcov``, not
    ``glm``'s expected-information ``cov_params()``).

    ``mu = log(e)`` always. ``s = s_sign / b``, where ``s_sign`` is ``+1`` for ``LN.2`` (whose
    ``b`` comes out positive on finney71) or ``-1`` for ``LL.2`` (whose ``b`` comes out
    negative) -- see ``tools/drc_reference/README.md``'s sign-convention note, empirically
    confirmed against ``predict()`` there, not assumed here. Jacobian, rows ``(mu, s)``,
    columns ``(b, e)``: ``d(mu)/d(b) = 0``, ``d(mu)/d(e) = 1/e``; ``d(s)/d(b) =
    -s_sign/b**2``, ``d(s)/d(e) = 0``.
    """
    jacobian = np.array(
        [
            [0.0, 1.0 / e],
            [-s_sign / b**2, 0.0],
        ]
    )
    return jacobian @ sigma_be @ jacobian.T


def _covariance_entry(fit_covariance: Any, name_a: str, name_b: str) -> float:
    i = fit_covariance.names.index(name_a)
    j = fit_covariance.names.index(name_b)
    return float(fit_covariance.matrix[i][j])


class TestFinney71Probit:
    """finney71, probit link, fixed ``upper=1.0, lower=0.0`` -- the GLM path (plan section
    5.1), against drc's ``LN.2`` and the independent ``glm`` fit, both in ``finney71.json``.
    """

    def test_mu_and_s_match_the_glm_and_drc_ln2_derivation(self) -> None:
        fixture = _load("finney71.json")
        glm = fixture["glm"]["probit"]
        beta0 = glm["coef"]["(Intercept)"]
        beta1 = glm["coef"]["log(dose)"]
        # Sign convention confirmed against predict() in generate.R (see finney71.json's
        # "mapping" block and tools/drc_reference/README.md): on finney71 (response=failure,
        # increasing with dose), LN.2's b comes out positive and mu=log(e), s=1/b.
        ln2 = fixture["drc"]["LN2"]
        assert ln2["coef"]["b:(Intercept)"] > 0.0
        expected_mu = -beta0 / beta1
        expected_s = 1.0 / beta1
        assert expected_mu == pytest.approx(
            math.log(ln2["coef"]["e:(Intercept)"]), rel=_REL_TOL_PARAMS
        )
        assert expected_s == pytest.approx(1.0 / ln2["coef"]["b:(Intercept)"], rel=_REL_TOL_PARAMS)

        obs = _finney71_observations()
        fit = fit_dose_response(obs, model="binomial", link="probit", upper=1.0, lower=0.0)

        assert fit.status is Status.OK
        assert fit.params is not None
        assert fit.params["mu"].value == pytest.approx(expected_mu, rel=_REL_TOL_PARAMS)
        assert fit.params["s"].value == pytest.approx(expected_s, rel=_REL_TOL_PARAMS)

    def test_mu_matches_mass_dose_p_ed50(self) -> None:
        """MASS ``dose.p`` at ``p=0.5``: an independent second source for the ED50, on the
        log(dose) scale directly (see finney71.json's ``mass_dose_p`` note: dose.p applies no
        inverse transform for a transformed covariate, so its "Dose" output is already ``mu``).
        """
        fixture = _load("finney71.json")
        expected_mu = fixture["mass_dose_p"]["dose"]

        obs = _finney71_observations()
        fit = fit_dose_response(obs, model="binomial", link="probit", upper=1.0, lower=0.0)

        assert fit.params is not None
        assert fit.params["mu"].value == pytest.approx(expected_mu, rel=_REL_TOL_PARAMS)

    def test_log_likelihood_matches_drc_and_glm(self) -> None:
        fixture = _load("finney71.json")
        expected = fixture["drc"]["LN2"]["logLik"]
        assert fixture["glm"]["probit"]["logLik"] == pytest.approx(expected, rel=_REL_TOL_PARAMS)

        obs = _finney71_observations()
        fit = fit_dose_response(obs, model="binomial", link="probit", upper=1.0, lower=0.0)

        assert fit.log_likelihood == pytest.approx(expected, rel=_REL_TOL_PARAMS)

    def test_covariance_matches_delta_transformed_drc_ln2_vcov(self) -> None:
        """decisions/0007: covariance parity is against drc's ``LN.2`` ``vcov`` (observed
        information), not ``glm``'s expected-information ``cov_params()``. ``finney71.json``'s
        ``drc.LN2.observed_hessian_check`` independently confirms drc's ``vcov`` really is the
        observed information here (matches an independently-computed numerical Hessian to
        within about 1e-6 relative on this dataset), so it is a trustworthy reference despite
        coming from drc's own numerical optimizer.
        """
        fixture = _load("finney71.json")
        ln2 = fixture["drc"]["LN2"]
        b = ln2["coef"]["b:(Intercept)"]
        e = ln2["coef"]["e:(Intercept)"]
        sigma_be = _matrix(ln2["vcov"])
        expected_cov = _delta_transform_drc_be_covariance(b, e, s_sign=1.0, sigma_be=sigma_be)

        obs = _finney71_observations()
        fit = fit_dose_response(obs, model="binomial", link="probit", upper=1.0, lower=0.0)

        assert fit.covariance is not None
        assert set(fit.covariance.names) == {"mu", "s"}
        assert _covariance_entry(fit.covariance, "mu", "mu") == pytest.approx(
            expected_cov[0, 0], rel=_REL_TOL_COV
        )
        assert _covariance_entry(fit.covariance, "s", "s") == pytest.approx(
            expected_cov[1, 1], rel=_REL_TOL_COV
        )
        assert _covariance_entry(fit.covariance, "mu", "s") == pytest.approx(
            expected_cov[0, 1], rel=_REL_TOL_COV
        )


class TestFinney71Logit:
    """finney71, logit link, fixed ``upper=1.0, lower=0.0`` -- against drc's ``LL.2`` and the
    ``glm`` logit fit.
    """

    def test_mu_and_s_match_the_glm_and_drc_ll2_derivation(self) -> None:
        fixture = _load("finney71.json")
        glm = fixture["glm"]["logit"]
        beta0 = glm["coef"]["(Intercept)"]
        beta1 = glm["coef"]["log(dose)"]
        # Sign convention confirmed against predict() in generate.R: on finney71, LL.2's b
        # comes out NEGATIVE (unlike LN.2's positive b), and mu=log(e), s=-1/b.
        ll2 = fixture["drc"]["LL2"]
        assert ll2["coef"]["b:(Intercept)"] < 0.0
        expected_mu = -beta0 / beta1
        expected_s = 1.0 / beta1
        assert expected_mu == pytest.approx(
            math.log(ll2["coef"]["e:(Intercept)"]), rel=_REL_TOL_PARAMS
        )
        assert expected_s == pytest.approx(-1.0 / ll2["coef"]["b:(Intercept)"], rel=_REL_TOL_PARAMS)

        obs = _finney71_observations()
        fit = fit_dose_response(obs, model="binomial", link="logit", upper=1.0, lower=0.0)

        assert fit.status is Status.OK
        assert fit.params is not None
        assert fit.params["mu"].value == pytest.approx(expected_mu, rel=_REL_TOL_PARAMS)
        assert fit.params["s"].value == pytest.approx(expected_s, rel=_REL_TOL_PARAMS)

    def test_log_likelihood_matches_drc_ll2(self) -> None:
        fixture = _load("finney71.json")
        expected = fixture["drc"]["LL2"]["logLik"]

        obs = _finney71_observations()
        fit = fit_dose_response(obs, model="binomial", link="logit", upper=1.0, lower=0.0)

        assert fit.log_likelihood == pytest.approx(expected, rel=_REL_TOL_PARAMS)

    def test_covariance_matches_delta_transformed_drc_ll2_vcov(self) -> None:
        """decisions/0007, mirroring ``TestFinney71Probit``'s ``LN.2`` check: covariance parity
        against drc's ``LL.2`` ``vcov``, cross-checked in ``finney71.json`` against an
        independently-computed observed-information Hessian.
        """
        fixture = _load("finney71.json")
        ll2 = fixture["drc"]["LL2"]
        b = ll2["coef"]["b:(Intercept)"]
        e = ll2["coef"]["e:(Intercept)"]
        sigma_be = _matrix(ll2["vcov"])
        expected_cov = _delta_transform_drc_be_covariance(b, e, s_sign=-1.0, sigma_be=sigma_be)

        obs = _finney71_observations()
        fit = fit_dose_response(obs, model="binomial", link="logit", upper=1.0, lower=0.0)

        assert fit.covariance is not None
        assert set(fit.covariance.names) == {"mu", "s"}
        assert _covariance_entry(fit.covariance, "mu", "mu") == pytest.approx(
            expected_cov[0, 0], rel=_REL_TOL_COV
        )
        assert _covariance_entry(fit.covariance, "s", "s") == pytest.approx(
            expected_cov[1, 1], rel=_REL_TOL_COV
        )
        assert _covariance_entry(fit.covariance, "mu", "s") == pytest.approx(
            expected_cov[0, 1], rel=_REL_TOL_COV
        )


class TestGlmPathMatchesLikelihoodPathNearBoundary:
    """decisions/0007's path-consistency lock-in: a ``u=1, l=0`` fit (the GLM special case,
    decisions/0004) and the same data fit with ``upper``/``lower`` pinned a hair inside
    ``(0, 1)`` (``upper=1-1e-12, lower=1e-12`` -- not exactly ``1.0``/``0.0``, so this takes
    the ``GenericLikelihoodModel`` path, and pinned close enough to the boundary that the two
    curves are, for this purpose, the same curve) should report the same ``(mu, s)``
    covariance, since both sides are marginkit's own computation of the same quantity. Held at
    the full ``1e-4`` relative (decisions/0007's amendment), not a looser path-consistency
    allowance: this checks internal agreement, not parity against drc, so there is no excuse
    for a wider tolerance. Do not widen this if it fails; report the actual gap instead.
    """

    def test_covariance_matches_between_the_two_fitting_paths(self) -> None:
        obs = _finney71_observations()

        fit_glm_path = fit_dose_response(obs, model="binomial", link="probit", upper=1.0, lower=0.0)
        fit_likelihood_path = fit_dose_response(
            obs, model="binomial", link="probit", upper=1.0 - 1e-12, lower=1e-12
        )

        assert fit_glm_path.status is Status.OK
        assert fit_likelihood_path.status is Status.OK
        assert fit_glm_path.covariance is not None
        assert fit_likelihood_path.covariance is not None
        assert set(fit_likelihood_path.covariance.names) == {"mu", "s"}

        for name_a, name_b in (("mu", "mu"), ("s", "s"), ("mu", "s")):
            glm_value = _covariance_entry(fit_glm_path.covariance, name_a, name_b)
            likelihood_value = _covariance_entry(fit_likelihood_path.covariance, name_a, name_b)
            assert likelihood_value == pytest.approx(glm_value, rel=_REL_TOL_PATH_CONSISTENCY)


class TestEstimatedAsymptoteParity:
    """The seeded simulated dataset in ``estimated_asymptotes.json``, fit with marginkit's
    ``GenericLikelihoodModel`` path (D7 / ``decisions/0004``) and compared to drc's binomial
    ``LN.3`` (``upper="estimate", lower=0.0``) and ``LN.4`` (``upper="estimate",
    lower="estimate"``).

    **This class does not use plan section 6.1's usual 1e-4 relative bound, and that is
    recorded here and in ``tools/drc_reference/README.md``, not silently loosened.** drc's
    *default* fit (``drmc()``'s ``relTol=1e-7``) is under-converged on this dataset: refitting
    from the default fit's own coefficients with ``drmc(relTol=1e-14, maxIt=10000,
    method="BFGS")`` (the fixture's ``"tight"`` block, which is what this class reads --
    never ``"default"``) raises drc's own log-likelihood further, and marginkit's
    ``GenericLikelihoodModel`` path reaches a log-likelihood at or above even that tight
    refit's. Comparing coefficients at 1e-4 relative against an optimizer that has not itself
    converged to that precision would be comparing against noise, not against a reference
    value, so:

    - (a) log-likelihood is checked as an inequality, ``marginkit >= drc_tight - 1e-6``, not an
      equality band -- marginkit is expected to do at least as well as drc's tight refit;
    - (b) ``mu`` is compared with an **absolute** tolerance of ``1e-4``, because the simulation's
      true ``mu`` is exactly ``0``, where a relative tolerance is ill-posed (dividing by ~0);
    - (c) ``s``, ``upper`` and ``lower`` are compared at a **relative 1e-3**, one order looser
      than the usual parameter bound, matching the precision the tight refit itself reached.

    No other tolerance in this file is affected: the fixed-asymptote GLM tests above still use
    the plan's ordinary 1e-4 relative bound, because that path has an exact, fully-converged
    drc/glm reference to compare against.
    """

    _LOGLIK_INEQUALITY_SLACK = 1e-6
    _ABS_TOL_MU = 1e-4
    _REL_TOL_LOOSE = 1e-3

    @staticmethod
    def _observations() -> tuple[Observations, dict[str, Any]]:
        fixture = _load("estimated_asymptotes.json")
        sim = fixture["simulation"]
        axis = Axis(name="severity", unit="unit", scale="log")
        obs = Observations.from_counts(
            axis,
            severity=sim["severity"],
            successes=sim["successes"],
            trials=sim["trials"],
            outcome="success",
            direction="decreasing",
        )
        return obs, fixture

    def test_upper_estimate_lower_fixed_matches_drc_ln3(self) -> None:
        obs, fixture = self._observations()
        ln3 = fixture["drc"]["LN3"]["tight"]
        # Sign convention confirmed against predict() in generate.R (README.md): fit on
        # successes (decreasing curve), b comes out negative, mu=log(e), s=-1/b, upper=d,
        # lower=0 (fixed by drc's own LN.3).
        assert ln3["coef"]["b:(Intercept)"] < 0.0
        expected_mu = math.log(ln3["coef"]["e:(Intercept)"])
        expected_s = -1.0 / ln3["coef"]["b:(Intercept)"]
        expected_upper = ln3["coef"]["d:(Intercept)"]

        fit = fit_dose_response(obs, model="binomial", link="probit", upper="estimate", lower=0.0)

        assert fit.status is Status.OK
        assert fit.params is not None
        assert fit.params["mu"].value == pytest.approx(expected_mu, abs=self._ABS_TOL_MU)
        assert fit.params["s"].value == pytest.approx(expected_s, rel=self._REL_TOL_LOOSE)
        assert fit.params["upper"].value == pytest.approx(expected_upper, rel=self._REL_TOL_LOOSE)
        assert fit.params["lower"].value == 0.0
        assert fit.params["lower"].fixed is True
        assert fit.log_likelihood is not None
        assert fit.log_likelihood >= ln3["logLik"] - self._LOGLIK_INEQUALITY_SLACK

    def test_upper_estimate_lower_estimate_matches_drc_ln4(self) -> None:
        obs, fixture = self._observations()
        ln4 = fixture["drc"]["LN4"]["tight"]
        assert ln4["coef"]["b:(Intercept)"] < 0.0
        expected_mu = math.log(ln4["coef"]["e:(Intercept)"])
        expected_s = -1.0 / ln4["coef"]["b:(Intercept)"]
        expected_upper = ln4["coef"]["d:(Intercept)"]
        expected_lower = ln4["coef"]["c:(Intercept)"]

        fit = fit_dose_response(
            obs, model="binomial", link="probit", upper="estimate", lower="estimate"
        )

        assert fit.status is Status.OK
        assert fit.params is not None
        assert fit.params["mu"].value == pytest.approx(expected_mu, abs=self._ABS_TOL_MU)
        assert fit.params["s"].value == pytest.approx(expected_s, rel=self._REL_TOL_LOOSE)
        assert fit.params["upper"].value == pytest.approx(expected_upper, rel=self._REL_TOL_LOOSE)
        assert fit.params["lower"].value == pytest.approx(expected_lower, rel=self._REL_TOL_LOOSE)
        assert fit.log_likelihood is not None
        assert fit.log_likelihood >= ln4["logLik"] - self._LOGLIK_INEQUALITY_SLACK
