"""Recovery test for the estimated-asymptote path (plan section 4, Files table: "the
estimated-asymptote fit recovers simulated true parameters").

Reuses the same seeded simulated dataset as the drc reference fixture
(``tools/drc_reference/estimated_asymptotes.json``, generated by
``tools/drc_reference/generate.R``; a rich design -- 10 log-spaced levels plus a zero control,
n=400 per level) so the same fixed-seed data backs both the drc numerical-parity check
(``tests/reference/test_models_drc.py``) and this truth-recovery check, rather than inventing a
second simulated dataset with its own seed.

Tolerance is loose and standard-error-based, not a fixed number: truth must fall within 4
standard errors of the fitted value for each of the four parameters, per the brief.
"""

from __future__ import annotations

import json
import math
from pathlib import Path
from typing import Any

from marginkit import Axis, Observations, Status, fit_dose_response

_FIXTURE_PATH = (
    Path(__file__).resolve().parents[2] / "tools" / "drc_reference" / "estimated_asymptotes.json"
)


def _load_fixture() -> dict[str, Any]:
    with _FIXTURE_PATH.open() as fh:
        result: dict[str, Any] = json.load(fh)
    return result


def _standard_error(fit: Any, name: str) -> float:
    assert fit.covariance is not None
    i = fit.covariance.names.index(name)
    variance = fit.covariance.matrix[i][i]
    return math.sqrt(variance)


def test_estimated_upper_and_lower_recover_the_simulated_truth_within_4_se() -> None:
    fixture = _load_fixture()
    sim = fixture["simulation"]
    true_params = sim["true_params"]

    axis = Axis(name="severity", unit="unit", scale="log")
    obs = Observations.from_counts(
        axis,
        severity=sim["severity"],
        successes=sim["successes"],
        trials=sim["trials"],
        outcome="success",
        direction="decreasing",
    )

    fit = fit_dose_response(
        obs, model="binomial", link="probit", upper="estimate", lower="estimate"
    )

    assert fit.status is Status.OK
    assert fit.params is not None

    for name in ("mu", "s", "upper", "lower"):
        fitted_value = fit.params[name].value
        truth = true_params[name]
        se = _standard_error(fit, name)
        assert abs(fitted_value - truth) <= 4.0 * se, (
            f"{name}: fitted={fitted_value!r}, truth={truth!r}, se={se!r}, "
            f"|diff|={abs(fitted_value - truth)!r} exceeds 4*se={4.0 * se!r}"
        )
